application: balioldboys
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

libraries:
- name: PIL
  version: "latest"
- name: MySQLdb
  version: "latest"
- name: ssl 
  version: "latest"


inbound_services:
- warmup

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'
- url: /static
  static_dir: STATIC_URL


- url: /.*
  script: djangoappengine.main.application


skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(static/.*)$
- ^(env/.*)$
- ^(libds/.*)$
- ^(sqlite3.db)$
- ^(fixtures/.*)$
- ^(.*/)?\.sh$
- ^(.*/)?\.json$
- ^(.*/)?\.db$

